version: '2'
services:
    osnoregservice-app:
        image: osnoregservice
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://osnoregservice-postgresql:5432/osnoregservice
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    osnoregservice-postgresql:
        extends:
            file: postgresql.yml
            service: osnoregservice-postgresql
